cloud:
  config:
    fail-fast: true
    retry:
      useRandomPolicy: true
      max-interval: 6000

spring:

  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  application:
    name: analyzer

  config:
    import: configserver:http://localhost:8888